# @package _global_

dataset:
  view_sampler:
    index_path: assets/evaluation_index_replica_nctx2.json

evaluation:
  methods:
    - name: Ours
      key: ours
      path: baselines/replica/ours/frames
    - name: Du et al.~\cite{du2023cross}
      key: du2023
      path: baselines/replica/yilun/frames
    - name: GPNR~\cite{suhail2022generalizable}
      key: gpnr
      path: baselines/replica/gpnr/frames
    - name: pixelNeRF~\cite{pixelnerf}
      key: pixelnerf
      path: baselines/replica/pixelnerf/frames

  side_by_side_path: null
  animate_side_by_side: false

output_metrics_path: baselines/replica/evaluation_metrics.json